# -*- coding: utf-8 -*-
"""Matching_Antiratmask_behaviour_simulataneous_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuFw5BDdyX5mTTsL6SD1DMFGH5_kSQoO

# Plotting all of the masks / behaviour together
"""

#Behaviour masks
import numpy as np
import tifffile
import napari

behaviour = '/Users/cli/Documents/JY316/Behaviour/Process masks /or_plane0_seg.npy'
behaviour_data = np.load(behaviour, allow_pickle=True).item()
behaviour_or_0 = behaviour_data['masks']

behaviour = '/Users/cli/Documents/JY316/Behaviour/Process masks /or_plane1_seg.npy'
behaviour_data = np.load(behaviour, allow_pickle=True).item()
behaviour_or_1 = behaviour_data['masks']

behaviour = '/Users/cli/Documents/JY316/Behaviour/Process masks /or_plane2_seg.npy'
behaviour_data = np.load(behaviour, allow_pickle=True).item()
behaviour_or_2 = behaviour_data['masks']

behaviour = '/Users/cli/Documents/JY316/Behaviour/Process masks /pyr_plane0_seg.npy'
behaviour_data = np.load(behaviour, allow_pickle=True).item()
behaviour_pyr_0 = behaviour_data['masks']

behaviour = '/Users/cli/Documents/JY316/Behaviour/Process masks /pyr_plane1_seg.npy'
behaviour_data = np.load(behaviour, allow_pickle=True).item()
behaviour_pyr_1 = behaviour_data['masks']

behaviour = '/Users/cli/Documents/JY316/Behaviour/Process masks /pyr_plane2_seg.npy'
behaviour_data = np.load(behaviour, allow_pickle=True).item()
behaviour_pyr_2 = behaviour_data['masks']

import numpy as np
import napari

#All masks registered to the in vivo stack
file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo14_merscope22_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
print(seg_data.keys())
masks22 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo13_merscope21_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks21 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo12_merscope20_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks20 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo11_merscope19_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks19 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo31_merscope18_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks18 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo21_merscope17_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks17 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo22_merscope16_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks16 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo23_merscope15_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks15 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo24_merscope14_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks14 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo25_merscope13_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks13 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo35_merscope12_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks12 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo34_merscope11_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks11 = seg_data['masks']

file ='/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo33_merscope10_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks10 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo32_merscope9_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks9 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo41_merscope5_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks5 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo42_merscope4_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks4 = seg_data['masks']

file = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo43_merscope3_invivo.seg.npy'
seg_data = np.load(file, allow_pickle=True).item()
masks3 = seg_data['masks']

import numpy as np
import pickle

gene_reg19_11 = tifffile.imread('/Users/cli/Documents/JY316/vid/region19/reg19_gene_invivo.tif')
gene_reg19_11 = gene_reg19_11[:,:,:,0]
gene_reg20_12 = tifffile.imread('/Users/cli/Documents/JY316/vid/region20/reg20_gene_invivo.tif')
gene_reg20_12 = gene_reg20_12[:,:,:,0]
gene_reg21_13 = tifffile.imread('/Users/cli/Documents/JY316/vid/region21/reg21_gene_invivo.tif')
gene_reg21_13 = gene_reg21_13[:,:,:,0]
gene_reg22_14 = tifffile.imread('/Users/cli/Documents/JY316/vid/region22/reg22_gene_invivo.tif')
gene_reg22_14 = gene_reg22_14[:,:,:,0]

gene_reg17_21 = tifffile.imread('/Users/cli/Documents/JY316/vid/region17/reg17_gene_invivo.tif')
gene_reg17_21 = gene_reg17_21[:,:,:,0]
gene_reg16_22 = tifffile.imread('/Users/cli/Documents/JY316/vid/region16/reg16_gene_invivo.tif')
gene_reg16_22 = gene_reg16_22[:,:,:,0]
gene_reg15_23 = tifffile.imread('/Users/cli/Documents/JY316/vid/region15/reg15_gene_invivo.tif')
gene_reg15_23 = gene_reg15_23[:,:,:,0]
gene_reg14_24 = tifffile.imread('/Users/cli/Documents/JY316/vid/region14/reg14_gene_invivo.tif')
gene_reg14_24 = gene_reg14_24[:,:,:,0]
gene_reg13_25 = tifffile.imread('/Users/cli/Documents/JY316/vid/region13/reg13_gene_invivo.tif')
gene_reg13_25 = gene_reg13_25[:,:,:,0]

gene_reg18_31 = tifffile.imread('/Users/cli/Documents/JY316/vid/region18/reg18_gene_invivo.tif')
gene_reg18_31 = gene_reg18_31[:,:,:,0]
gene_reg9_32 = tifffile.imread('/Users/cli/Documents/JY316/vid/region9/reg9_gene_invivo.tif')
gene_reg9_32 = gene_reg9_32[:,:,:,0]
gene_reg10_33 = tifffile.imread('/Users/cli/Documents/JY316/vid/region10/reg10_gene_invivo.tif')
gene_reg10_33 = gene_reg10_33[:,:,:,0]
gene_reg11_34 = tifffile.imread('/Users/cli/Documents/JY316/vid/region11/reg11_gene_invivo.tif')
gene_reg11_34 = gene_reg11_34[:,:,:,0]
gene_reg12_35 = tifffile.imread('/Users/cli/Documents/JY316/vid/region12/reg12_gene_invivo.tif')
gene_reg12_35 = gene_reg12_35[:,:,:,0]

gene_reg5_41 = tifffile.imread('/Users/cli/Documents/JY316/vid/region5/reg5_gene_invivo.tif')
gene_reg5_41 = gene_reg5_41 [:,:,:,0]
gene_reg4_42 = tifffile.imread('/Users/cli/Documents/JY316/vid/region4/reg4_gene_invivo.tif')
gene_reg4_42 = gene_reg4_42[:,:,:,0]
gene_reg3_43 = tifffile.imread('/Users/cli/Documents/JY316/vid/region3/reg3_gene_invivo.tif')
gene_reg3_43 = gene_reg3_43 [:,:,:,0]

import tifffile
import napari
import pickle
import numpy as np

#Launch all of the masks and files in napari

def manual_histogram_normalization(image):
    img_min = np.min(image)
    img_max = np.max(image)
    normalized_image = (image - img_min) / (img_max - img_min)
    scaled_image = (normalized_image * 255).astype(np.uint8)
    return scaled_image

invivo = tifffile.imread('/Users/cli/Documents/JY316/in_vivo/JY316_in_Vivo_stack_flipped.tif')
invivo = manual_histogram_normalization(invivo)
exvivo = tifffile.imread('/Users/cli/Documents/JY316/ex-vivo/exvivo_total.tif')
exvivo = manual_histogram_normalization(exvivo)

viewer = napari.Viewer()
viewer.add_image(invivo,colormap='red', blending='additive')
viewer.add_image(exvivo,colormap='bop blue', blending='additive')
#viewer.add_image(mask,colormap='purple', blending='additive')
viewer.add_image(gene_reg19_11,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg20_12,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg21_13,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg22_14,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg17_21,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg16_22,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg15_23,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg14_24,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg13_25,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg18_31,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg9_32,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg10_33,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg11_34,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg12_35,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg5_41,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg4_42,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg3_43,colormap='bop blue', blending='additive')
viewer.add_image(behaviour_or_0,colormap='green', blending='additive')
viewer.add_image(behaviour_or_1,colormap='green', blending='additive')
viewer.add_image(behaviour_or_2,colormap='green', blending='additive')
viewer.add_image(behaviour_pyr_0,colormap='green', blending='additive')
viewer.add_image(behaviour_pyr_1,colormap='green', blending='additive')
viewer.add_image(behaviour_pyr_2,colormap='green', blending='additive')
viewer.add_image(masks3,colormap='magenta', blending='additive')
viewer.add_image(masks4,colormap='magenta', blending='additive')
viewer.add_image(masks5,colormap='magenta', blending='additive')
viewer.add_image(masks9,colormap='magenta', blending='additive')
viewer.add_image(masks10,colormap='magenta', blending='additive')
viewer.add_image(masks11,colormap='magenta', blending='additive')
viewer.add_image(masks12,colormap='magenta', blending='additive')
viewer.add_image(masks13,colormap='magenta', blending='additive')
viewer.add_image(masks14,colormap='magenta', blending='additive')
viewer.add_image(masks15,colormap='magenta', blending='additive')
viewer.add_image(masks16,colormap='magenta', blending='additive')
viewer.add_image(masks17,colormap='magenta', blending='additive')
viewer.add_image(masks18,colormap='magenta', blending='additive')
viewer.add_image(masks19,colormap='magenta', blending='additive')
viewer.add_image(masks20,colormap='magenta', blending='additive')
viewer.add_image(masks21,colormap='magenta', blending='additive')
viewer.add_image(masks22,colormap='magenta', blending='additive')
napari.run()

import tifffile
import napari
import pickle
import numpy as np

#Launch all of the masks and files in napari for the gene video

def manual_histogram_normalization(image):
    img_min = np.min(image)
    img_max = np.max(image)
    normalized_image = (image - img_min) / (img_max - img_min)
    scaled_image = (normalized_image * 255).astype(np.uint8)
    return scaled_image

invivo = tifffile.imread('/Users/cli/Documents/JY316/in_vivo/JY316_in_Vivo_stack_flipped.tif')
invivo = manual_histogram_normalization(invivo)
exvivo = tifffile.imread('/Users/cli/Documents/JY316/ex-vivo/exvivo_total.tif')
exvivo = manual_histogram_normalization(exvivo)

viewer = napari.Viewer()
viewer.add_image(invivo,colormap='green', blending='additive')
viewer.add_image(exvivo,colormap='magenta', blending='additive')
#viewer.add_image(mask,colormap='purple', blending='additive')
viewer.add_image(gene_reg19_11,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg20_12,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg21_13,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg22_14,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg17_21,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg16_22,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg15_23,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg14_24,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg13_25,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg18_31,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg9_32,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg10_33,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg11_34,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg12_35,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg5_41,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg4_42,colormap='bop blue', blending='additive')
viewer.add_image(gene_reg3_43,colormap='bop blue', blending='additive')
"""
viewer.add_image(behaviour_or_0,colormap='green', blending='additive')
viewer.add_image(behaviour_or_1,colormap='green', blending='additive')
viewer.add_image(behaviour_or_2,colormap='green', blending='additive')
viewer.add_image(behaviour_pyr_0,colormap='green', blending='additive')
viewer.add_image(behaviour_pyr_1,colormap='green', blending='additive')
viewer.add_image(behaviour_pyr_2,colormap='green', blending='additive')"""
napari.run()

merscope = tifffile.imread('/Users/cli/Documents/JY316/Merscope/19/mosaic_Anti-Rat_z4.tif')
gene_merscope_img = tifffile.imread('/Users/cli/Documents/JY316/Merscope/19/gene_scatter_single_channel.tif')


viewer = napari.Viewer()
viewer.add_image(merscope,colormap='green', blending='additive')
viewer.add_image(gene_merscope_img,colormap='magenta', blending='additive')

napari.run()

"""# Counting the number of cells matched and the number of in vivo masks to determine recovery rate"""

import os
import pandas as pd

def count_total_rows(csv_directory):
    total_rows = 0

    # Iterate through all files in the directory
    for file_name in os.listdir(csv_directory):
        if file_name.endswith(".csv"):
            file_path = os.path.join(csv_directory, file_name)
            try:
                df = pd.read_csv(file_path)
                # Subtract 1 to skip header row (if not empty)
                row_count = max(len(df) - 1, 0)
                total_rows += row_count
            except Exception as e:
                print(f"Error reading {file_name}: {e}")

    return total_rows

# Set your directory
csv_directory = "/Users/cli/Documents/JY316/Final Matching/Antirat_ROI_to_behaviour_ROI/"
total_rows = count_total_rows(csv_directory)

print(f"Total number of data rows (excluding headers): {total_rows}")

import numpy as np

# List all masks
all_masks = [
    behaviour_or_0, behaviour_or_1, behaviour_or_2,
    behaviour_pyr_0, behaviour_pyr_1, behaviour_pyr_2
]

# Count total number of unique nonzero labels
total_labels = 0
label_counts = {}

for i, mask in enumerate(all_masks):
    labels = np.unique(mask)
    labels = labels[labels != 0]  # exclude background
    count = len(labels)
    total_labels += count
    label_counts[f'mask_{i}'] = count

print("Label counts per mask:", label_counts)
print("Total labeled regions across all masks:", total_labels)