# -*- coding: utf-8 -*-
"""save_to_tif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EJaWfOfHo9p6C-5vUL42yg7I7Nd4FEe3
"""

# packages
import numpy as np
import pandas as pd
import os, json
import tifffile as tif
import geopandas as gp
import matplotlib.pyplot as plt

from scipy import ndimage

# Load files
gene_xy       = pd.read_csv('/Users/cli/Documents/JY316/vid/region19/detected_transcripts.csv')

micron2mosaic = np.loadtxt('/Users/cli/Documents/JY316/vid/region19/micron_to_mosaic_pixel_transform.csv', delimiter = ' ')
cell_parq     = gp.read_parquet('/Users/cli/Documents/JY316/vid/region19/cellpose2_micron_space.parquet')

z_number   = 4

with open('/Users/cli/Documents/JY316/vid/region19/manifest.json', 'r') as f:
    region_metadata = json.load(f)

gene_xy_downsampled = gene_xy
gene_xy_downsampled = gene_xy_downsampled[['global_x', 'global_y']].to_numpy()
gene_xy_downsampled = np.hstack([gene_xy_downsampled, np.ones((gene_xy_downsampled.shape[0], 1))])
gene_xy_mosaic = gene_xy_downsampled @ micron2mosaic.T

W = region_metadata['mosaic_width_pixels']
H = region_metadata['mosaic_height_pixels']

# Black background
img = np.zeros((H, W), dtype=np.uint8)
x = gene_xy_mosaic[:, 0]
y = gene_xy_mosaic[:, 1]

xi = np.floor(x).astype(int)
yi = np.floor(y).astype(int)

mask = (xi >= 0) & (xi < W) & (yi >= 0) & (yi < H)

img[yi[mask], xi[mask]] = 255  # white points

dot_radius = 2

for dx in range(-dot_radius, dot_radius + 1):
    for dy in range(-dot_radius, dot_radius + 1):
        if dx*dx + dy*dy <= dot_radius*dot_radius:
            xii = xi + dx
            yii = yi + dy

            mask2 = (
                (xii >= 0) & (xii < W) &
                (yii >= 0) & (yii < H)
            )

            img[yii[mask2], xii[mask2]] = 255

tif.imwrite(
    "/Users/cli/Documents/JY316/Merscope/19/gene_scatter_single_channel_bigdot.tif",
    img )

# downsample as necessary
# gene_xy_downsampled = gene_xy[gene_xy['global_z'] == z_number]
gene_xy_downsampled = gene_xy
# gene_xy_downsampled = gene_xy_downsampled[gene_xy_downsampled['gene'] == 'Wfs1']
gene_xy_downsampled = gene_xy_downsampled[['global_x', 'global_y']].to_numpy()
gene_xy_downsampled = np.hstack([gene_xy_downsampled, np.ones((gene_xy_downsampled.shape[0], 1))])

# transform to mosaic space
gene_xy_mosaic = gene_xy_downsampled @ micron2mosaic.T

rna_downsample_factor = 50 # downsample for visualization

plt.figure(figsize=(5,5))
plt.scatter( gene_xy_mosaic[::rna_downsample_factor,0],  gene_xy_mosaic[::rna_downsample_factor,1], alpha = 0.5, s = 10)

x = gene_xy_mosaic[:, 0]
y = gene_xy_mosaic[:, 1]

print(f"  x: min = {x.min():.2f}, max = {x.max():.2f}")
print(f"  y: min = {y.min():.2f}, max = {y.max():.2f}")

print("Width  (pixels):", x.max() - x.min())
print("Height (pixels):", y.max() - y.min())

# Construct bins
with open('/Users/cli/Documents/JY316/vid/region21_resegmentation/manifest.json', 'r') as f:
    region_metadata = json.load(f)

xy_mosaic = [region_metadata['mosaic_width_pixels'], region_metadata['mosaic_height_pixels']]
xbins     = np.arange(0, xy_mosaic[0]+1, 1)
ybins     = np.arange(0, xy_mosaic[1]+1, 1)

print(f"  x: min = {xbins.min():.2f}, max = {xbins.max():.2f}")
print(f"  y: min = {ybins.min():.2f}, max = {ybins.max():.2f}")

gene_xy_downsampled = gene_xy
# gene_xy_downsampled = gene_xy_downsampled[gene_xy_downsampled['gene'] == 'Wfs1']
gene_xy_downsampled = gene_xy_downsampled[['global_x', 'global_y']].to_numpy()
gene_xy_downsampled = np.hstack([gene_xy_downsampled, np.ones((gene_xy_downsampled.shape[0], 1))])

# transform to mosaic space
gene_xy_mosaic = gene_xy_downsampled @ micron2mosaic.T

b = tif.imread('/Users/cli/Documents/JY316/Merscope/21/mosaic_DAPI_z4.tif')
b = np.fliplr(b)
print(b.shape)

g = tif.imread('/Users/cli/Documents/JY316/vid/region21_resegmentation/mosaic_Cellbound3_z4.tif')
print(g.shape)

import numpy as np
import tifffile as tif

W = region_metadata['mosaic_width_pixels']
H = region_metadata['mosaic_height_pixels']

# Black background
img = np.zeros((H, W), dtype=np.uint8)
x = gene_xy_mosaic[:, 0]
y = gene_xy_mosaic[:, 1]

xi = np.floor(x).astype(int)
yi = np.floor(y).astype(int)

mask = (xi >= 0) & (xi < W) & (yi >= 0) & (yi < H)

img[yi[mask], xi[mask]] = 255  # white points
tif.imwrite(
    "/Users/cli/Documents/JY316/Merscope/21/gene_scatter_single_channel.tif",
    img )

fig, axes = plt.subplots(1, 1, figsize=(20,10), sharex=True, sharey=True)
axes.imshow(g, origin='lower')
axes.scatter(gene_xy_mosaic[:, 0], gene_xy_mosaic[:, 1], s=0.0095, color='red')

W = region_metadata['mosaic_width_pixels']
H = region_metadata['mosaic_height_pixels']

print(W, H)


fig, ax = plt.subplots(figsize=(20, 10))

ax.imshow(b, origin="lower", cmap="gray")
ax.scatter(
    gene_xy_mosaic[:, 0],
    gene_xy_mosaic[:, 1],
    s=0.01,
    c="red"
)

ax.set_xlim(0, W)
ax.set_ylim(0, H)
ax.axis("off")

plt.show()

# RNA density

# Construct bins
with open('manifest.json', 'r') as f:
    region_metadata = json.load(f)

xy_mosaic = [region_metadata['mosaic_width_pixels'], region_metadata['mosaic_height_pixels']]
xbins     = np.arange(0, xy_mosaic[0]+1, 1)
ybins     = np.arange(0, xy_mosaic[1]+1, 1)


# gene_xy_downsampled = gene_xy[gene_xy['global_z'] == z_number]
gene_xy_downsampled = gene_xy
gene_xy_downsampled = gene_xy_downsampled[['global_x', 'global_y']].to_numpy()
gene_xy_downsampled = np.hstack([gene_xy_downsampled, np.ones((gene_xy_downsampled.shape[0], 1))])
gene_xy_mosaic = gene_xy_downsampled @ micron2mosaic.T

rna_downsample_factor = 400  # downsample for visualization

plt.figure(figsize=(5, 5))
plt.scatter(
    gene_xy_mosaic[::rna_downsample_factor, 0],
    gene_xy_mosaic[::rna_downsample_factor, 1],
    alpha=0.5,
    s=10
)

plt.axis("equal")        # important for spatial data
plt.axis("off")          # optional

plt.savefig(
    "/Users/cli/Documents/JY316/Merscope/21/gene.tif",
    dpi=300,              # good for publications
    format="tiff",   # <-- prevents auto-cropping
    pad_inches=0
)

plt.close()

import numpy as np
import matplotlib.pyplot as plt

# Scatter bounds (from your printout)
xmin, xmax = 100.06, 18616.80
ymin, ymax = 100.07, 14913.00

W = xmax - xmin   # ~18517 px
H = ymax - ymin   # ~14813 px

dpi = 300

fig_w = W / dpi
fig_h = H / dpi

fig, ax = plt.subplots(figsize=(fig_w, fig_h), dpi=dpi)

rna_downsample_factor = 100

plt.scatter( gene_xy_mosaic[::rna_downsample_factor,0],  gene_xy_mosaic[::rna_downsample_factor,1], alpha = 0.5, s = 20)

# FORCE bounds
ax.set_xlim(xmin, xmax)
ax.set_ylim(ymax, ymin)   # flip Y for image-style coords

ax.axis("off")

fig.savefig(
    "/Users/cli/Documents/JY316/Merscope/21/gene.tif",
    format="tiff",
    dpi=dpi,
    bbox_inches=None,
    pad_inches=0
)

plt.close(fig)

import numpy as np
import matplotlib.pyplot as plt
import tifffile as tiff # You may need to install this: pip install tifffile
from io import BytesIO

# --- Your existing setup code ---
xmin, xmax = 100.06, 18616.80
ymin, ymax = 100.07, 14913.00
W = xmax - xmin # ~18517 px
H = ymax - ymin # ~14813 px
dpi = 300
fig_w = W / dpi
fig_h = H / dpi

fig, ax = plt.subplots(figsize=(fig_w, fig_h), dpi=dpi)
# Assuming 'gene_xy_mosaic' and 'rna_downsample_factor' are defined in your environment
# ax.scatter( gene_xy_mosaic[::rna_downsample_factor, 0], gene_xy_mosaic[::rna_downsample_factor, 1], s=1, alpha=0.5 )

# Example scatter data if variables are undefined
gene_xy_mosaic = np.random.rand(1000, 2) * [W, H] + [xmin, ymin]
rna_downsample_factor = 1
ax.scatter(gene_xy_mosaic[::rna_downsample_factor, 0], gene_xy_mosaic[::rna_downsample_factor, 1], s=1, alpha=0.5, color='black') # Set color to black

# FORCE bounds
ax.set_xlim(xmin, xmax)
ax.set_ylim(ymax, ymin) # flip Y for image-style coords
ax.axis('off') # Note the quotes around 'off'

# --- The saving part ---

# 1. Render the figure to an in-memory buffer as a NumPy array (RGBA)
fig.canvas.draw()
rgba_image = np.array(fig.canvas.renderer.buffer_rgba())

# 2. Convert the RGBA image to grayscale (single channel luminance 'L')
# A common method is weighted average: L = 0.2989*R + 0.5870*G + 0.1140*B
# If your points are black on white background, you can simply take one channel (e.g., Red)
# and invert the colors if needed, but a proper conversion is better:
gray_image = np.dot(rgba_image[...,:1], [0.2989, 0.5870, 0.1140]).astype(np.uint8)

# 3. Use tifffile to save the single-channel array as a TIFF
output_path = '/Users/cli/Documents/JY316/Merscope/21/gene_grayscale.tif'
tiff.imwrite(output_path, gray_image, photometric='minisblack')

plt.close(fig)
print(f"Saved grayscale image to {output_path}")

import tifffile
from PIL import Image, ImageOps

img2 = tifffile.imread('/Users/cli/Documents/JY316/Merscope/21/mosaic_Anti-Rat_z4.tif')
print(img2.shape)

img1 = tifffile.imread('/Users/cli/Documents/JY316/Merscope/21/gene.tif')
img1 = img1[:,:,1]
print(img1.shape)
#padded_img = ImageOps.pad(img1, (15013, 18717), color='white')
#print(paded_img)

img3 = tifffile.imread('/Users/cli/Documents/JY316/Merscope/21/mosaic_DAPI_z4.tif')
img3 = np.fliplr(img3)
print(img3.shape)

import napari

viewer = napari.Viewer()
viewer.add_image(img1)
viewer.add_image(img2)
viewer.add_image(img3)
napari.run()

def write_vpt_mosaic(path, region_id, z_index, r, force_uint16=True, imagej=True, key_='RNA'):
    # 1) clean up values
    r = np.nan_to_num(r, nan=0.0, posinf=0.0, neginf=0.0)

    # 2) choose dtype
    if force_uint16:
        # scale to 0..65535 consistently across Z (per stain) — do this with fixed scale
        r_min, r_max = r.min(), r.max()
        if r_max > r_min:
            r_scaled = (r - r_min) / (r_max - r_min)
        else:
            r_scaled = np.zeros_like(r, dtype=np.float32)
        r_out = (r_scaled * 65535.0).astype(np.uint16)
    else:
        # Fiji is happier with float32 than float64
        r_out = r.astype(np.float32)

    # 3) enforce 2D YX grayscale, no channel dimension
    assert r_out.ndim == 2, "Expected a 2D array per z (YX)."

    # 4) write a Fiji-friendly TIFF
    out_path = os.path.join(path, f"region_{region_id}", "images", f"mosaic_{key_}_z{z_index}.tif")
    imwrite(
        out_path,
        r_out,
        photometric='minisblack',  # grayscale
        contiguous=True,
        bigtiff='auto',
        compression=None,          # or 'zlib' if you want smaller files
        metadata=None,             # avoid weird extra tags
        imagej=imagej              # makes Fiji very happy for plain YX stacks
    )
    return out_path

import numpy as np
from tifffile import imwrite
import os

for z_ in range(1, 8, 2):

    if z_ > 0 and z_ < 7:
        gene_mask = (gene_xy['global_z'] >= (z_-1)) & (gene_xy['global_z'] <= (z_+1))
    elif z_ == 0:
        gene_mask = (gene_xy['global_z'] <= (z_+2))
    else:
        gene_mask = gene_xy['global_z'] >= (z_-2)

    gene_xy_downsampled = gene_xy[gene_mask]
    # gene_xy_downsampled = gene_xy
    gene_xy_downsampled = gene_xy_downsampled[['global_x', 'global_y']].to_numpy()
    gene_xy_downsampled = np.hstack([gene_xy_downsampled, np.ones((gene_xy_downsampled.shape[0], 1))])
    gene_xy_mosaic = gene_xy_downsampled @ micron2mosaic.T

    r, _, _ = np.histogram2d(gene_xy_mosaic[:,1], gene_xy_mosaic[:,0], bins=[ybins, xbins])
    r = ndimage.maximum_filter(r, size=5)
    r = ndimage.gaussian_filter(r, sigma=10)

    write_vpt_mosaic(path_metadata, region_id, z_, r, force_uint16=True, imagej=True)

    tif.imwrite(os.path.join(path_metadata, f'region_{region_id}', 'images', f'mosaic_RNA_z{z_}.tiff'), r)

# save
# RGB_stack = np.stack(RGB_stack, axis=0)
# tif.imwrite(os.path.join(output_path, f'region_{region_id}2.tif'), RGB_stack)