# -*- coding: utf-8 -*-
"""Video_file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vseR0bDCfFVW8QYGTSRHqIgPxoXN8JD9

# The video making script for JY316
"""

from skimage.transform import warp
from scipy.ndimage import zoom
import numpy as np
import scipy.ndimage as ndi
from scipy.ndimage import affine_transform
import tifffile

def trans_w_deform_2_channel(source, T_dict, o_shape, is_label=False):
    # Ensure the input is (Z, X, Y, C) and convert to (C, Z, X, Y)
    source = np.moveaxis(source, -1, 0)  # Move channel to first dimension
    C = source.shape[0]  # Number of channels

    all_vec_f_3 = np.zeros(tuple(o_shape) + (3,))
    B = np.eye(4)

    for l in T_dict:
        for k, v in l.items():
            if k == 'bhat':
                B = B @ (np.c_[v, np.array((0, 0, 0, 1))])
            if k == 'scale':
                B[:, :3] *= v
            if k == 'vec_field_total':
                vf = np.stack([pad3d(v[..., c], out_shape=o_shape) for c in range(3)], -1)
                all_vec_f_3 += vf

    R_3 = (np.linalg.inv(B[:3, :3])).T
    offset_3 = -B[-1, :-1] @ np.linalg.inv(B[:3, :3])

    print('Running rigid transformation...')
    transformed_all = np.array([
        ndi.affine_transform(
            source[c].astype('float32'),  # Transform per channel
            R_3,
            offset=offset_3,
            output_shape=o_shape,
            order=0 if is_label else 1  # Nearest-neighbor for labels
        ) for c in range(C)
    ])

    mapz_base, mapx_base, mapy_base = np.meshgrid(
        np.arange(o_shape[0]),
        np.arange(o_shape[1]),
        np.arange(o_shape[2]),
        indexing='ij'
    )
    mapz = mapz_base - all_vec_f_3[:, :, :, 0]
    mapx = mapx_base - all_vec_f_3[:, :, :, 1]
    mapy = mapy_base - all_vec_f_3[:, :, :, 2]

    print('Running deformable transformation...')
    deformed_all = np.array([
        warp(
            transformed_all[c],
            np.array((mapz, mapx, mapy)),
            order=0 if is_label else 1  # Nearest-neighbor for labels
        ) for c in range(C)
    ])

    print('Done.')

    # Convert back to (Z, X, Y, C) format
    deformed_all = np.moveaxis(deformed_all, 0, -1)

    return deformed_all


def trans_w_deform(source, T_dict, o_shape, is_label=False):
    assert(len(source.shape) == 4)  # Ensure (c, z, x, y)
    all_vec_f_3 = np.zeros(tuple(o_shape) + (3,))
    C = source.shape[0]
    B = np.eye(4)
    for l in T_dict:
        for k, v in l.items():
            if k == 'bhat':
                B = B @ (np.c_[v, np.array((0, 0, 0, 1))])
            if k == 'scale':
                B[:, :3] *= v
            if k == 'vec_field_total':
                vf = np.stack([pad3d(v[..., c], out_shape=o_shape) for c in range(3)], -1)
                all_vec_f_3 += vf
    R_3 = (np.linalg.inv(B[:3, :3])).T
    offset_3 = -B[-1, :-1] @ np.linalg.inv(B[:3, :3])

    print('Running rigid transformation...')
    transformed_all = np.array([
        ndi.affine_transform(
            source[c].astype('float32'),
            R_3,
            offset=offset_3,
            output_shape=o_shape,
            order=0 if is_label else 1  # Nearest-neighbor for labels
        ) for c in range(C)
    ])
    mapz_base, mapx_base, mapy_base = np.meshgrid(
        np.arange(o_shape[0]),
        np.arange(o_shape[1]),
        np.arange(o_shape[2]),
        indexing='ij'
    )
    mapz = mapz_base - all_vec_f_3[:, :, :, 0]
    mapx = mapx_base - all_vec_f_3[:, :, :, 1]
    mapy = mapy_base - all_vec_f_3[:, :, :, 2]
    print('Running deformable transformation...')
    deformed_all = np.array([
        warp(
            transformed_all[c],
            np.array((mapz, mapx, mapy)),
            order=0 if is_label else 1  # Nearest-neighbor for labels
        ) for c in range(C)
    ])
    print('Done.')
    return deformed_all

def pad3d(a,out_shape):
    assert(len(a.shape)==3)
    assert(len(a.shape)==len(out_shape))

    out =a[:out_shape[0],:out_shape[1],:out_shape[2]]
    # else:
    #     print("the outshape is actually smaller than the input, we need to crop the original instead")
    #     out = np.zeros(out_shape)
    #     out[:a.shape[0], :a.shape[1],:a.shape[2]] = a
    return out

"""# Transform transcripts into merscope shape before it was registered to exvivo form + then register to exvivo"""

import tifffile
import numpy as np
from scipy.ndimage import zoom
from skimage.transform import warp
from scipy.ndimage import zoom
import scipy.ndimage as ndi
from scipy.ndimage import map_coordinates
from scipy.ndimage import affine_transform
import pickle


#dat = '/Users/cli/Documents/JY316/Segmentation/masks/exvivo25_merscope13_combined_seg.npy' # tif image of transcript instead
dat = '/Users/cli/Documents/JY316/Merscope/12/gene_scatter_single_channel.tif'

#original exvivo image
exvivo = tifffile.imread('/Users/cli/Documents/JY316/ex-vivo/downsampled/3_5.tif')
#merscope to exvivo transformation
transformation_M = '/Users/cli/Documents/JY316/Registration/merscope_to_exvivo/3_5_reg12_transformed_20250523_124011.pkl'
#Path and file name to save the masks transformed to 'exvivo'
overlay_tiff_path = '/Users/cli/Documents/JY316/vid/region12/reg12_gene_exvivo.tif'
#overlay_tiff_path = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo25_merscope13_exvivo.tif'

"""
dat = '/Users/cli/Documents/JY316/Segmentation/masks/exvivo13_merscope21_combined_seg.npy'
dat = np.load(dat, allow_pickle=True).item()
original_mask = dat['masks'] #Downsampled by 4!! # just load .tif image instead
print(original_mask.shape)
mask_data = zoom(original_mask, (4, 4), order=0)  # Adjust zoom factors as needed
print("Resized mask shape:", mask_data.shape)
mask_data = np.expand_dims(mask_data , axis=0)
mask_data = zoom(mask_data,(2, 0.108, 0.108),order=0) #The adjustment to the merscope file in 3D_napari_merscope_to_exvivo.ipynb
mask_data = np.expand_dims(mask_data , axis=0) # Match Channel dimensions
print(mask_data.shape)

with open(transformation_M, 'rb') as file:
    data = pickle.load(file)
transformation_M= data['transformations']

#Transformation
transformed_mask_to_exvivo = trans_w_deform(
    mask_data,
    transformation_M,
    exvivo.shape,
    is_label=True
)
print(transformed_mask_to_exvivo.shape)


dat1 = '/Users/cli/Documents/JY316/Merscope/21/gene_scatter_single_channel.tif'
original_mask = tifffile.imread(dat1)
mask_data1 = np.fliplr(original_mask) #Extra due to dapi being in whatever way
print("Resized mask shape:", mask_data1.shape)

"""

#All neccessary processing to do mask data to get into the same shape the merscope image was in before registered to exvivo image

"""
dat = '/Users/cli/Documents/JY316/Segmentation/masks/exvivo13_merscope21_combined_seg.npy'
dat = np.load(dat, allow_pickle=True).item()
original_mask = dat['masks'] #Downsampled by 4!! # just load .tif image instead
print(original_mask.shape)
mask_data = zoom(original_mask, (4, 4), order=0)  # Adjust zoom factors as needed"""

original_mask = tifffile.imread(dat)
mask_data = np.fliplr(original_mask) #Extra due to dapi being in whatever way

print("Resized mask shape:", mask_data.shape)
mask_data = np.expand_dims(mask_data , axis=0)
mask_data = zoom(mask_data,(2, 0.108, 0.108),order=0) #The adjustment to the merscope file in 3D_napari_merscope_to_exvivo.ipynb
mask_data = np.expand_dims(mask_data , axis=0) # Match Channel dimensions
print(mask_data.shape)

with open(transformation_M, 'rb') as file:
    data = pickle.load(file)
transformation_M= data['transformations']

#Transformation
transformed_mask_to_exvivo = trans_w_deform(
    mask_data,
    transformation_M,
    exvivo.shape,
    is_label=True

)
print(transformed_mask_to_exvivo.shape)

"""# Save in the form it was in in the exvivo before transformed to invivo"""

#Putting the transformed mask into two channels and saving it
def crop_array(arr, target_shape = exvivo.shape):
    target_z, target_x, target_y = target_shape
    cropped_arr = arr[:target_z, :target_x, :target_y]
    return cropped_arr

transformed_mask_to_exvivo_adjust = np.squeeze(transformed_mask_to_exvivo)  # shape: (Y, X)
transformed_mask_to_exvivo_adjust[1] = transformed_mask_to_exvivo_adjust[0] # Copy Z=0 into Z=1
merscope_cropped = crop_array(transformed_mask_to_exvivo_adjust)
merscope_cropped = zoom(merscope_cropped, (1.5, 1, 1), order=0)
print(merscope_cropped.shape)

overlay_image = np.zeros((*merscope_cropped.shape, 3))  # (Z, Y, X, 3)
overlay_image[..., 0] = merscope_cropped  # Red
overlay_image[..., 1] = merscope_cropped  # Green
print(overlay_image.shape)
#tifffile.imwrite(overlay_tiff_path, overlay_image)

#Check Visulation - ensure all transformations are correct
import napari
original_image = tifffile.imread('/Users/cli/Documents/JY316/Registration/antirat_to_invivo/combined_image/3_5_merscope12.tif')
print(original_image.shape)
img_for_mask = tifffile.imread('/Users/cli/Documents/JY316/Segmentation/exvivo35_merscope12_combined.tif')

#Remember the mask has to be in all 2 ones
viewer = napari.Viewer()
viewer.add_image(transformed_mask_to_exvivo)
viewer.add_image(original_image)
viewer.add_image(overlay_image)
viewer.add_image(img_for_mask)
napari.run()

"""# Transform to invivo"""

#Load files - mask tranformed to exvivo, transformation, and invivo image
import pickle

img_seg_mask = tifffile.imread('/Users/cli/Documents/JY316/vid/region12/reg12_gene_exvivo.tif') #Shape of the transcript transformed in the exvivo form
print(img_seg_mask.shape)
output_invivo = '/Users/cli/Documents/JY316/vid/region12/reg12_gene_invivo.tif'

file = '/Users/cli/Documents/JY316/Registration/antirat_to_invivo/3_5_merscope12transformed_20250530123120.pkl'
with open(file, 'rb') as file:
    data = pickle.load(file)
    print(data.keys())
transformation_invivo = data['transformations']
transformed = data['transformed']
print(transformed.shape)

invivo = tifffile.imread('/Users/cli/Documents/JY316/in_vivo/JY316_in_Vivo_stack_flipped.tif')

# Apply the second transformation
transformed_mask_to_invivo = trans_w_deform_2_channel(
    img_seg_mask,
    transformation_invivo,
    invivo.shape
)

print("Final transformed mask shape:", transformed_mask_to_invivo.shape)

tifffile.imwrite(output_invivo,transformed_mask_to_invivo)

#Check
import napari
viewer = napari.Viewer()
viewer.add_image(transformed_mask_to_invivo[:,:,:,0])
viewer.add_image(transformed[0,:,:,:])
viewer.add_image(invivo)
napari.run()

dat = '/Users/cli/Documents/JY316/Merscope/21/gene_scatter_single_channel.tif'
original_mask = tifffile.imread(dat)
mask_data = np.fliplr(original_mask)

antirat = tifffile.imread('/Users/cli/Documents/JY316/Merscope/21/mosaic_Anti-Rat_z4.tif')

viewer = napari.Viewer()
viewer.add_image(mask_data)
viewer.add_image(antirat)
#viewer.add_image(overlay_image)
napari.run()

"""# Save as .tif image in that format

# Transform transcript .tif files into the exvivo form
"""

registration_file = '/Users/cli/Documents/JY316/Registration/merscope_to_exvivo/1_1_reg19_transformed_20250522_160646.pkl'
with open(registration_file, 'rb') as file:
    data = pickle.load(file)
transformation_11 = data['transformations']

exvivo_11 = tifffile.imread('/Users/cli/Documents/JY316/ex-vivo/pkl/1_1.pkl')

img =

Merscope_mask_inexvivoform = trans_w_deform(img, transformation_11, exvivo_11.shape)

import tifffile
import numpy as np
from scipy.ndimage import zoom
from skimage.transform import warp
from scipy.ndimage import zoom
import scipy.ndimage as ndi
from scipy.ndimage import map_coordinates
from scipy.ndimage import affine_transform
import pickle

#Segmentation masks
dat = '/Users/cli/Documents/JY316/Segmentation/masks/exvivo25_merscope13_combined_seg.npy' #Replace with a .tif image up here ^


#original exvivo image
exvivo = tifffile.imread('/Users/cli/Documents/JY316/ex-vivo/downsampled/2_5.tif')
#merscope to exvivo transformation
transformation_M = '/Users/cli/Documents/JY316/Registration/merscope_to_exvivo/2_5_reg13_transformed_20250523_113116.pkl'
#Path and file name to save the masks transformed to 'exvivo'
overlay_tiff_path = '/Users/cli/Documents/JY316/Segmentation/matched_masks/exvivo25_merscope13_exvivo.tif'

#All neccessary processing to do mask data to get into the same shape the merscope image was in before registered to exvivo image

image = tifffile.imread(dat)

dat = np.load(dat, allow_pickle=True).item()
original_mask = dat['masks'] #Downsampled by 4!!\\
mask_data = zoom(original_mask, (4, 4), order=0)  # Adjust zoom factors as needed
print("Resized mask shape:", mask_data.shape)
mask_data = np.expand_dims(mask_data , axis=0)
mask_data = zoom(mask_data,(2, 0.108, 0.108),order=0) #The adjustment to the merscope file in 3D_napari_merscope_to_exvivo.ipynb
mask_data = np.expand_dims(mask_data , axis=0) # Match Channel dimensions
print(mask_data.shape)

with open(transformation_M, 'rb') as file:
    data = pickle.load(file)
transformation_M= data['transformations']

#Transformation
transformed_mask_to_exvivo = trans_w_deform(
    mask_data,  =
    transformation_M,
    exvivo.shape,
    is_label=True
)

# Confirm files

import napari
viewer = napari.Viewer()
viewer.add_image(exvivo_11)
viewer.add_image(Merscope_mask_inexvivoform)
napari.run()

"""# Transform it to the stack"""

